"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""
from pathlib import Path
from decouple import config                 # Required for SECRET_KEY and DEBUG
import dj_database_url                      # Required for dynamic database configuration
import os                                   # Required for static file path generation

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- CORE SECURITY & DEBUG SETTINGS (Using python-decouple) ---
# SECURITY WARNING: keep the secret key used in production secret!
# Reads SECRET_KEY from a .env file locally, or from environment variable in production.
SECRET_KEY = config('SECRET_KEY') 

# SECURITY WARNING: don't run with debug turned on in production!
# Reads DEBUG from a .env file (e.g., DEBUG=True) or defaults to False in production.
DEBUG = config('DEBUG', default=False, cast=bool)

# Define allowed hosts (your local and live domains)
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'your-render-name.onrender.com']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'calculator.apps.MyappConfig',
    # NOTE: If you are using WhiteNoise, you don't need to add it here, 
    # but make sure it is installed via pip!
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # --- START WHITENOISE CONFIGURATION ---
    # Add WhiteNoise middleware right after SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware", 
    # --- END WHITENOISE CONFIGURATION ---
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], # <-- Correct template directory setup
        'APP_DIRS': True, 
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# --- DATABASE CONFIGURATION (Production Ready) ---
# Uses dj_database_url to parse the 'DATABASE_URL' environment variable 
# (provided by Render/Heroku/Railway).
# For local development, this defaults to the SQLite DB if DATABASE_URL is not set in .env.
DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
    )
}


# Password validation
# (No changes needed here)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- STATIC FILES CONFIGURATION (WhiteNoise) ---
# All production settings must define STATIC_ROOT
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

# Configure WhiteNoise to compress and cache static files
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# --- END STATIC FILES CONFIGURATION ---


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'